export {default as navPage} from './nav-page'
export {default as navLink} from './nav-link'
export {default as navStatic} from './nav-static'
export {default as person} from './person'
export {default as pageSection} from './page-section'
